### PR TITLE
Break off gcp tips page

### PR DESCRIPTION
**Pull request by christiam**

### CODE REVIEW

**Comment by tom6931** [comment]
I think this is fine and it's a good idea to highlight the console.  I did have an issue getting it to run, but I'm done for today, so we can look next week.

**Review by tom6931 — APPROVED** [review]
I think this is fine and it's a good idea to highlight the console.  I did have an issue getting it to run, but I'm done for today, so we can look next week.

**Review by victzh — APPROVED** [review]

**Comment by tom6931** [comment]
It seems that "sudo apt-get install -yq kubectl python3-distutils" does not work on ubuntu.  See attached screenshot.  If I drop kubectl (and do that separately), it does work.

Screen Shot 2020-11-16 at 8 49 28 AM

**Comment by christiam** [comment]
> It seems that "sudo apt-get install -yq kubectl python3-distutils" does not work on ubuntu. See attached screenshot. If I drop kubectl (and do that separately), it does work.
> 
> Screen Shot 2020-11-16 at 8 49 28 AM

Thanks for the feedback @tom6931 . It's advisable that the command below is executed beforehand, but it was not in the documentation:

    sudo apt-get -yqm update

I created the pull request below for that https://github.com/elb-colleagues/elbdoc/pull/34

**Pull request merged**
